name: PowderTracker
options:
  bundleIdPrefix: com.shredders
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    version: 2.18.0
  Nuke:
    url: https://github.com/kean/Nuke
    from: 12.7.0
  SwiftUIShimmer:
    url: https://github.com/markiv/SwiftUI-Shimmer
    from: 1.5.0
  ConfettiSwiftUI:
    url: https://github.com/simibac/ConfettiSwiftUI
    from: 1.1.0
  TelemetryDeck:
    url: https://github.com/TelemetryDeck/SwiftSDK
    from: 2.3.0

targets:
  PowderTracker:
    type: application
    platform: iOS
    sources:
      - PowderTracker
    entitlements:
      path: PowderTracker/PowderTracker.entitlements
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.shredders.powdertracker
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "PowderTracker"
        CODE_SIGN_ENTITLEMENTS: PowderTracker/PowderTracker.entitlements
    dependencies:
      - target: PowderTrackerWidgetExtension
        embed: true
      - package: Supabase
        products:
          - Supabase
          - Auth
          - PostgREST
          - Storage
          - Realtime
      - package: Nuke
        products:
          - Nuke
          - NukeUI
      - package: SwiftUIShimmer
        products:
          - Shimmer
      - package: ConfettiSwiftUI
        products:
          - ConfettiSwiftUI
      - package: TelemetryDeck
        products:
          - TelemetryDeck

  PowderTrackerWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: PowderTrackerWidget
        excludes:
          - "**/.DS_Store"
          - "**/Info.plist"
      - path: PowderTracker/Models
        name: Models
    info:
      path: PowderTrackerWidget/Info.plist
      properties:
        CFBundleDisplayName: "PowderTracker Widget"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shredders.powdertracker.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES

schemes:
  PowderTracker:
    build:
      targets:
        PowderTracker: all
        PowderTrackerWidgetExtension: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
